### ISSUE TITLE
error Library not loaded: /usr/local/opt/mysql-client/lib/libssl.1.1.dylib

### ISSUE THREAD

**Issue by dinager** [PyMySQL/mysqlclient#546]
### Describe the bug

```
Uncaught exception!
Traceback (most recent call last):
  File "/Users/myname/my-app/some/path/sqlalchemy_db_profiling.py", line 10, in <module>
    from MySQLdb.converters import conversions, escape
  File "/Users/myname/my-app/venv/lib/python3.7/site-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: dlopen(/Users/myname/my-app/venv/lib/python3.7/site-packages/MySQLdb/_mysql.cpython-37m-darwin.so, 2): 
  Library not loaded: /usr/local/opt/mysql-client/lib/libssl.1.1.dylib
      Referenced from: /Users/myname/my-app/venv/lib/python3.7/site-packages/MySQLdb/_mysql.cpython-37m-darwin.so
      Reason: image not found
```
**installed package:**
mysqlclient==1.4.6

### Environment

- OS: macOS 11.4 (Big Sur)

- Python: pyenv Python 3.7.10

- Connector/C: Homebrew mysql-client 8.0.29

- Openssl: Brew openssl@1.1

**Comment by methane** [comment]
* Create clean venv
* Clear pip cache. (wheel cache may contain old binary linking old client library).
* Follow what `brew info mysql-client` said. e.g. `export PKG_CONFIG_PATH="/usr/local/opt/mysql-client/lib/pkgconfig"`
* Install again.
