### ISSUE TITLE
Problem using executemany with an ON DUPLICATE KEY UPDATE statement

### ISSUE THREAD

**Issue by alanwsmith** [PyMySQL/mysqlclient#549]
### Describe the bug

I'm having problems using `.executemany()` with an `ON DUPLICATE KEY UPDATE` statement. 

The issue I'm seeing is that if I have a sql statement like:

```sql
INSERT INTO executemany_test (a_key, a_value)
VALUES (%s, %s)
ON DUPLICATE KEY UPDATE a_value = %s
```
with a payload like:

```python
payload = [
('eeee', 'Name E', 'Name E'),
('ffff', 'Name F', 'Name F')
]
```

and run it like this:

```python
cursor.executemany(sql, payload)
```
It throws an error like this:

```
Traceback (most recent call last):
  File "/Users/alan/Desktop/tmp.py", line 74, in <module>
    this_does_not_work()
  File "/Users/alan/Desktop/tmp.py", line 65, in this_does_not_work
    cursor.executemany(sql_with_update, payload)
  File "/opt/homebrew/lib/python3.9/site-packages/MySQLdb/cursors.py", line 230, in executemany
    return self._do_execute_many(
  File "/opt/homebrew/lib/python3.9/site-packages/MySQLdb/cursors.py", line 255, in _do_execute_many
    v = values % escape(next(args), conn)
TypeError: not all arguments converted during bytes formatting

shell returned 1
```

If I use `.execute()` with a single row of data with the same update statement things work as expected. The problem is only occurring with `.executemany()`. 

### To Reproduce

I've got an example script that makes preps a table and demonstrates the issue. I'll post it as the next comment since it's long.

### Environment

**MySQL Server**

- I'm using PlanetScale for the server
- I'm having trouble figuring out the version but this post points to them using Vitess 9: https://planetscale.com/blog/announcing-vitess-9

**MySQL Client**

- OS: macOS 12.2.1

- Python: Homebrew Python 3.9.13

- Python module: mysqlclient 2.1.1

- Connector/C): Homebrew mysql  Ver 8.0.29 for macos12.4 on arm64 - (I don't see a mysql-client anywhere so I'm not sure if this is the info you need here)

**Comment by alanwsmith** [comment]
Here's the script I setup to reproduce the issue

```python
#!/usr/bin/env python3

import MySQLdb


conn = MySQLdb.connect(
    host = 'the_host',
    db = 'the_db',
    user = 'the_user',
    passwd = 'the_passwd'
)

cursor = conn.cursor()


sql_basic = """
    INSERT INTO executemany_test (a_key, a_value)
    VALUES (%s, %s)"""

sql_with_update = """
    INSERT INTO executemany_test (a_key, a_value)
    VALUES (%s, %s)
    ON DUPLICATE KEY UPDATE a_value = %s"""

def prep():
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS executemany_test
        (a_key VARCHAR(255) PRIMARY KEY, a_value VARCHAR(255))""")
    cursor.execute("""TRUNCATE TABLE executemany_test""")


def this_works_1():
    payload = ('aaaa', 'Name A')
    cursor.execute(sql_basic, payload)
    conn.commit()


def this_works_2():
    payload = [
        ('bbbb', 'Name B'), ('cccc', 'Name C')
    ]
    cursor.executemany(sql_basic, payload)
    conn.commit()


def this_works_3():
    payload = ('dddd', 'Name D', 'Name D')
    cursor.execute(sql_with_update, payload)
    conn.commit()


def this_does_not_work():
    payload = [
        ('eeee', 'Name E', 'Name E'),
        ('ffff', 'Name F', 'Name F')
    ]
    cursor.executemany(sql_with_update, payload)
    conn.commit()


if __name__ == "__main__":
    prep()
    this_works_1()
    this_works_2()
    this_works_3()
    this_does_not_work()
```

**Comment by methane** [comment]
Don't use executemany(). Build bulk update query manually or with tools building SQL.
