### ISSUE TITLE
Error resolving libs of mariadb and amazon linux 2023

### ISSUE THREAD

**Issue by matejsp** [PyMySQL/mysqlclient#629]
### Describe the bug

It does not work by default.
It works if I copy pc file like this:
cp /usr/lib64/pkgconfig/libmariadb.pc /usr/lib64/pkgconfig/mysqlclient.pc

```

  Complete output (22 lines):

  Trying pkg-config --exists mysqlclient

  Command 'pkg-config --exists mysqlclient' returned non-zero exit status 1.

  Trying pkg-config --exists mariadb

  Command 'pkg-config --exists mariadb' returned non-zero exit status 1.

  Traceback (most recent call last):

    File "/source/python39/lib64/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>

      main()

    File "/source/python39/lib64/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main

      json_out['return_val'] = hook(**hook_input['kwargs'])

    File "/source/python39/lib64/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel

      return hook(config_settings)

    File "/tmp/pip-build-env-n_jk1cp6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel

      return self._get_build_requires(config_settings, requirements=['wheel'])

    File "/tmp/pip-build-env-n_jk1cp6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires

      self.run_setup()

    File "/tmp/pip-build-env-n_jk1cp6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup

      exec(code, locals())

    File "<string>", line 154, in <module>

    File "<string>", line 48, in get_config_posix

    File "<string>", line 27, in find_package_name

  Exception: Can not find valid pkg-config name.

  Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
```

### Environment

Amazon Linux 2023

### How did you install libmysqlclient libraries?

dnf install -y mariadb-connector-c-devel pkgconfig

### Minimum but complete code to reproduce

```python
# Write Python code here.
import MySQLdb

conn = MySQLdb.connect(host='127.0.0.1', port=3306, user='root')
...
```

### Schema and initial data required to reproduce.

```sql
-- Write SQL here.
-- e.g. CREATE TABLE ...
```

**Comment by methane** [comment]
OK. I will add `libmariadb` to default pkg-config name list.
